### ISSUE TITLE
Does not install on Yosemite

### ISSUE THREAD

**Issue by Tekl** [Geremia/LatinDictionary#1]
The installer must be updated as it thinks 10.10 is below 10.5.

**Comment by Geremia** [comment]
I currently don't have a Mac OS X machine anymore to be able to remake the installer, but the files are all there if you want to use the installer maker utility included with XCode. You'd just have to modify  LatinDictionary/Latin.mpkg/Contents/distribution.dist and use the installer maker to remake the installer.

**Comment by Geremia** [comment]
@Tekl I've corrected this issue. Download [latin.dmg](https://github.com/Geremia/LatinDictionary/blob/master/latin.dmg) and see if it works now.

**Comment by Tekl** [comment]
Well, the installer is not signed, but it works.

**Comment by Geremia** [comment]
Does it complain about it not being signed? Was it signed before?

**Comment by Tekl** [comment]
Yes, OS X doesn't want to install it unless I open the installer via the contextual menu. I don't know if it was signed before.

**Comment by Geremia** [comment]
@Tekl I think that's normal for packages not downloaded from the App Store. I've encountered it before with other open-source projects I've installed from outside the App Store.

**Comment by Tekl** [comment]
You can codesign/add a certificate to an installer. You only need a developer certificate from Apple.
